### ISSUE TITLE
Form action triggers script on external website

### ISSUE THREAD

**Issue by therealmaxmoon** [PitiTheGrey/Habitican-Wardrobes#2]
I've cloned this project and looked over the code and I found that if the form is triggered an external site will be called:
https://github.com/PitiTheGrey/Habitican-Wardrobes/blob/9d93f18d8ec0f830e5d7e5d36e7506873eadb459/wardrobes.html#L3840
So every time someone is using this code on his/her/they own instance, the abbhh server will execute it.

A fix would be to delete the whole action block (`action="https://www.abbhh.de/wardrobes.html"`) so the page will call itself.

Thanks for this really useful tool. :)

**Comment by PitiTheGrey** [comment]
And thank you for such an important fix. I think the block found it's way into the code while doing some copy&paste or such. It was 
unintended. I have deleted it now.
