### ISSUE TITLE
Party Cron Times doesn't show all members

### ISSUE THREAD

**Issue by therealmaxmoon** [PitiTheGrey/Habitican-Wardrobes#3]
We are currently 12 people in the party, but the tool shows only 10 people in the list.

**Comment by PitiTheGrey** [comment]
I think it lists only those members who participate in the quest. I will have to throw an eye onto that. Thanks for reporting.

**Comment by PitiTheGrey** [comment]
I found a path to display all members. Bug is fixed now.

**Comment by PitiTheGrey** [comment]
Thanks a lot for commenting! (closed)
